# Generated by Django 2.2.12 on 2020-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facult', models.CharField(max_length=64)),
                ('spec', models.CharField(max_length=64)),
                ('year', models.PositiveSmallIntegerField(max_length=64)),
                ('number_of_students', models.PositiveSmallIntegerField(max_length=64)),
            ],
        ),
    ]
