# Generated by Django 2.2.12 on 2020-05-21 14:45

from django.db import migrations

from teachers.models import Teacher


def forwards(apps, schema):
    for t in Teacher.objects.all().iterator():
        t.first_name = str(t.first_name).capitalize()
        t.last_name = str(t.last_name).capitalize()
        t.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
