# Generated by Django 2.2.12 on 2020-05-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_logger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='created',
        ),
    ]
